### ISSUE TITLE
TypeError Cannot read properties of null

### ISSUE THREAD

**Issue by smarek** [ultrabolido/PrinceJS#6]
Game froze at this point in level 4

```
Uncaught TypeError: Cannot read properties of null (reading 'x')
    at PrinceJS.Kid.PrinceJS.Fighter.facingOpponent (Fighter.js:672:41)
    at PrinceJS.Enemy.PrinceJS.Fighter.checkFight (Fighter.js:269:28)
    at PrinceJS.Enemy.updateActor (Enemy.js:58:8)
    at PrinceJS.Game.updateWorld (Game.js:167:23)
    at c.Timer.update (phaser.min.js:19:10463)
    at c.Time.update (phaser.min.js:19:6552)
    at c.Game.update (phaser.min.js:12:3802)
    at c.RequestAnimationFrame.updateRAF (phaser.min.js:18:10004)
    at window.requestAnimationFrame.forceSetTimeOut._onLoop (phaser.min.js:18:9880)
```

Screenshot
![2021-12-29-104838_1655x1006_scrot](https://user-images.githubusercontent.com/384824/147649058-20dbceca-a570-453e-83a8-6b73d07da3ba.png)

**Comment by OsaSoft** [comment]
ditto, i ran into the same issue every time i went there 
![image](https://user-images.githubusercontent.com/8895463/147861423-1867f817-aee1-4e0c-8d03-059358be7fa9.png)

**Comment by ultrabolido** [comment]
princejs.com is a fork by @oklemenz. Contact with the author here [oklemenz](https://github.com/oklemenz/PrinceJS)

**Comment by oklemenz** [comment]
I could reproduce the error. It happens when going first right leaving the exit door, seeing the enemy, but then going left and then coming from below and from right to the same enemy again.

Going to this enemy is not necessary, as the level 4 is solved by going right not left, climbing from below up...

Nevertheless I will provide a fix asap... Thx for finding it.

**Comment by smarek** [comment]
@oklemenz thank you very much

**Comment by oklemenz** [comment]
Fix is deployed at princejs.com. Happy Playing!
